version: '2.2'
services:
    webserver:
        build: .
        restart: always
        environment:
            MYSQL_HOST:
            MYSQL_USER:
            MYSQL_PASSWORD:
            MYSQL_DATABASE:
            REDIS_HOST:
            REDIS_PASSWORD:
            AIRFLOW__WEBSERVER__AUTHENTICATE:
            AIRFLOW_USER:
            AIRFLOW_PASSWORD:
            LOAD_EX: 'n'
        volumes:
            - ./dags:/usr/local/airflow/dags
            # Uncomment to include custom plugins
            # - ./plugins:/usr/local/airflow/plugins
        ports:
            - "8080:8080"
        command: webserver -w ${AIRFLOW_WEBSERVER_NUMBER:-2}
        healthcheck:
            test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3

    flower:
        build: .
        restart: always
        environment:
            MYSQL_HOST:
            MYSQL_USER:
            MYSQL_PASSWORD:
            MYSQL_DATABASE:
            REDIS_HOST:
            REDIS_PASSWORD:
        ports:
            - "5555:5555"
        command: flower

    scheduler:
        build: .
        restart: always
        depends_on:
            - webserver
        volumes:
            - ./dags:/usr/local/airflow/dags
            # Uncomment to include custom plugins
            # - ./plugins:/usr/local/airflow/plugins
        environment:
            MYSQL_HOST:
            MYSQL_USER:
            MYSQL_PASSWORD:
            MYSQL_DATABASE:
            REDIS_HOST:
            REDIS_PASSWORD:
            LOAD_EX: 'n'
        command: scheduler --do_pickle

    worker:
        build: .
        restart: always
        volumes:
            # - ./dags:/usr/local/airflow/dags
            - ./requirements:/requirements
            # Uncomment to include custom plugins
            # - ./plugins:/usr/local/airflow/plugins
        environment:
            MYSQL_HOST:
            MYSQL_USER:
            MYSQL_PASSWORD:
            MYSQL_DATABASE:
            REDIS_HOST:
            REDIS_PASSWORD:
            LOAD_EX: 'n'
        command: worker --do_pickle -c ${AIRFLOW_WORKER_PROCESS_NUMBER:-8} -cn ${AIRFLOW_WORKER_NAME:-"worker"}
