version: '2.1'
services:
    webserver:
        build: .
        restart: always
        environment:
            MYSQL_HOST:
            MYSQL_USER:
            MYSQL_PASSWORD:
            MYSQL_DATABASE:
            REDIS_HOST:
            REDIS_PASSWORD:
            LOAD_EX: 'n'
            FERNET_KEY: '46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho='
        volumes:
            - ./dags:/usr/local/airflow/dags
            # Uncomment to include custom plugins
            # - ./plugins:/usr/local/airflow/plugins
        ports:
            - "8080:8080"
        command: webserver
        healthcheck:
            test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3

    flower:
        build: .
        restart: always
        environment:
            MYSQL_HOST:
            MYSQL_USER:
            MYSQL_PASSWORD:
            MYSQL_DATABASE:
            REDIS_HOST:
            REDIS_PASSWORD:
        ports:
            - "5555:5555"
        command: flower

    scheduler:
        build: .
        restart: always
        depends_on:
            - webserver
        volumes:
            - ./dags:/usr/local/airflow/dags
            # Uncomment to include custom plugins
            # - ./plugins:/usr/local/airflow/plugins
        environment:
            MYSQL_HOST:
            MYSQL_USER:
            MYSQL_PASSWORD:
            MYSQL_DATABASE:
            REDIS_HOST:
            REDIS_PASSWORD:
            LOAD_EX: 'n'
            FERNET_KEY: '46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho='
        command: scheduler

    worker:
        build: .
        restart: always
        volumes:
            - ./dags:/usr/local/airflow/dags
            - ./requirements:/requirements
            # Uncomment to include custom plugins
            # - ./plugins:/usr/local/airflow/plugins
        environment:
            MYSQL_HOST:
            MYSQL_USER:
            MYSQL_PASSWORD:
            MYSQL_DATABASE:
            REDIS_HOST:
            REDIS_PASSWORD:
            LOAD_EX: 'n'
            FERNET_KEY: '46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho='
        command: worker
