version: '2.1'
services:
    redis:
        image: 'redis:3.2.7'
        ports:
            - 6379:6379
        environment:
            # 从当前的环境变量中传递
            REDIS_HOST:
            REDIS_PASSWORD:
        command: redis-server --requirepass ${REDIS_PASSWORD}

    mysql:
        image: 'mysql:5.6'
        ports:
            - 3306:3306
        environment:
            MYSQL_HOST:
            MYSQL_USER:
            MYSQL_PASSWORD:
            MYSQL_DATABASE:
            MYSQL_ROOT_PASSWORD:
        volumes:
            - ./mysql/mysql.conf.d:/etc/mysql/mysql.conf.d
            # 解除注释可以将 MySQL 的数据保存至本地
            # - ./mysql/data:/var/lib/mysql

    webserver:
        build: .
        restart: always
        depends_on:
            - redis
            - mysql
        environment:
            MYSQL_HOST:
            MYSQL_USER:
            MYSQL_PASSWORD:
            MYSQL_DATABASE:
            REDIS_HOST:
            REDIS_PASSWORD:
            AIRFLOW__WEBSERVER__AUTHENTICATE:
            AIRFLOW_USER:
            AIRFLOW_PASSWORD:
            LOAD_EX: 'n'
            FERNET_KEY: '46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho='
        volumes:
            - ./dags:/usr/local/airflow/dags
            # Uncomment to include custom plugins
            # - ./plugins:/usr/local/airflow/plugins
        ports:
            - "8080:8080"
        command: webserver
        healthcheck:
            test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3

    flower:
        build: .
        restart: always
        depends_on:
            - redis
        environment:
            MYSQL_HOST:
            MYSQL_USER:
            MYSQL_PASSWORD:
            MYSQL_DATABASE:
            REDIS_HOST:
            REDIS_PASSWORD:
        ports:
            - "5555:5555"
        command: flower

    scheduler:
        build: .
        restart: always
        depends_on:
            - webserver
        volumes:
            - ./dags:/usr/local/airflow/dags
            # Uncomment to include custom plugins
            # - ./plugins:/usr/local/airflow/plugins
        environment:
            MYSQL_HOST:
            MYSQL_USER:
            MYSQL_PASSWORD:
            MYSQL_DATABASE:
            REDIS_HOST:
            REDIS_PASSWORD:
            LOAD_EX: 'n'
            FERNET_KEY: '46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho='
        command: scheduler

    worker:
        build: .
        restart: always
        volumes:
            - ./dags:/usr/local/airflow/dags
            - ./requirements:/requirements
            # Uncomment to include custom plugins
            # - ./plugins:/usr/local/airflow/plugins
        environment:
            MYSQL_HOST:
            MYSQL_USER:
            MYSQL_PASSWORD:
            MYSQL_DATABASE:
            REDIS_HOST:
            REDIS_PASSWORD:
            LOAD_EX: 'n'
            FERNET_KEY: '46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho='
        command: worker
